[workspace]
members = [
    "ngdp",

    "vixen_cas",
    "vixen_obj",
    "vixen_steamaudio",

    "vixen_bis_asset",
    "vixen_prometheus"
]
resolver = "2"

[patch.crates-io]
bevy = { version = "0.9", path = "../bevy" }
steamaudio = { path = "../steamaudio" }
